### ISSUE TITLE
Updates to AWS Prowler Report

### ISSUE THREAD

**Issue by kmccanless** [testdouble/devops-standards#14]
- [ The report should be able to run on CIS Level 1.  It currently runs but the pdf is empty except for the Header.] 
- [ A summary table show be after the introduction that shows the number of critical, highs, etc by region ]
- [ Document how to run prowler only is specific regions ]
- [ Nice to have - Keep the current working version of the pdf that works for CIS Level 2 and just update the introduction to be appropriate to that level. [Description of levels](https://www.cisecurity.org/cis-benchmarks/cis-benchmarks-faq#:~:text=The%20intent%20of%20the%20Level,environments%20where%20security%20is%20paramount.)]

**Comment by walkerab** [comment]
I've run a test and the report runs for CIS Level 1 without issue. @kmccanless Can you attach the commands you ran to generate the report and the pdf it generated?
